import * as XLSX from 'xlsx';
import type {ApartmentInput,Expense,ExpenseCategory,ExpenseInput} from './types';

export const REQUIRED_SHEETS=['Apartamento','Custos de Aquisição','Taxas de Obra'] as const;
export type ImportIssue={sheet:string;row?:number;message:string;kind:'ignored'|'warning'};
export type SpreadsheetExpense=Omit<ExpenseInput,'apartment_id'>;
export type ImportPreview={apartment:ApartmentInput;acquisitionCosts:SpreadsheetExpense[];constructionFees:SpreadsheetExpense[];issues:ImportIssue[]};

export const normalize=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
export function numberValue(value:unknown):number|null {if(typeof value==='number')return Number.isFinite(value)?value:null;if(typeof value!=='string'||!value.trim())return null;const raw=value.replace(/R\$\s?/gi,'').replace(/\s/g,'');const cleaned=raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw.replace(/,(?=\d{3}(?:\D|$))/g,'');const parsed=Number(cleaned);return Number.isFinite(parsed)?parsed:null}
export function dateValue(value:unknown):string|null {if(value instanceof Date&&!Number.isNaN(value.getTime()))return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;if(typeof value==='number'){const d=XLSX.SSF.parse_date_code(value);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null}if(typeof value!=='string'||!value.trim())return null;const text=value.trim(),br=text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/),iso=br?`${br[3]}-${br[2].padStart(2,'0')}-${br[1].padStart(2,'0')}`:text.slice(0,10);const parsed=new Date(`${iso}T12:00:00Z`);return Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==iso?null:iso}
const cell=(sheet:XLSX.WorkSheet,address:string)=>sheet[address]?.v;
const at=(sheet:XLSX.WorkSheet,column:number,row:number)=>cell(sheet,XLSX.utils.encode_cell({c:column,r:row-1}));
const range=(sheet:XLSX.WorkSheet)=>sheet['!ref']?XLSX.utils.decode_range(sheet['!ref']):{s:{r:0,c:0},e:{r:0,c:0}};
const labelValue=(sheet:XLSX.WorkSheet,patterns:RegExp[],fallback:string)=>{const bounds=range(sheet);for(let r=bounds.s.r;r<=bounds.e.r;r++)for(let c=bounds.s.c;c<=bounds.e.c;c++)if(patterns.some(p=>p.test(normalize(at(sheet,c,r+1)))))return at(sheet,c+1,r+1);return cell(sheet,fallback)};
const findHeaders=(sheet:XLSX.WorkSheet,expected:Record<string,RegExp[]>,fallbackRow=3)=>{const bounds=range(sheet);for(let row=bounds.s.r+1;row<=Math.min(bounds.e.r+1,15);row++){const found:Record<string,number>={};for(let column=bounds.s.c;column<=bounds.e.c;column++){const text=normalize(at(sheet,column,row));for(const [key,patterns] of Object.entries(expected))if(found[key]===undefined&&patterns.some(p=>p.test(text)))found[key]=column}if(Object.keys(found).length===Object.keys(expected).length)return{row,columns:found}}return{row:fallbackRow,columns:Object.fromEntries(Object.keys(expected).map((key,index)=>[key,index]))}};
const categoryFor=(category:unknown,description:unknown):ExpenseCategory|null=>{const text=normalize(`${category??''} ${description??''}`);if(/entrada|fgts/.test(text))return null;if(/taxa de obra/.test(text))return'construction_fee';if(/cartorio|registro/.test(text))return'registry';if(/imposto|itbi/.test(text))return'tax';if(/tarifa bancaria|tarifa/.test(text))return'bank_fee';if(/documentacao/.test(text))return'documentation';if(/avaliacao/.test(text))return'property_appraisal';if(/seguro/.test(text))return'insurance';return'other'};
const periodValue=(value:unknown)=>{const date=dateValue(value);if(date)return`${date.slice(5,7)}/${date.slice(0,4)}`;const match=String(value??'').trim().match(/(\d{1,2})[/-](\d{4})/);return match?`${match[1].padStart(2,'0')}/${match[2]}`:String(value??'').trim()};
const keyPart=(value:unknown)=>normalize(value).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const uniqueKey=(prefix:string,parts:unknown[],seen:Map<string,number>)=>{const base=`${prefix}:${parts.map(keyPart).join(':')}`,count=(seen.get(base)||0)+1;seen.set(base,count);return count===1?base:`${base}:${count}`};

export function parseWorkbook(workbook:XLSX.WorkBook,existingName='Apartamento',today=new Date().toISOString().slice(0,10)):ImportPreview {
 const missing=REQUIRED_SHEETS.filter(name=>!workbook.SheetNames.includes(name));if(missing.length)throw new Error(`Abas obrigatórias ausentes: ${missing.join(', ')}`);
 const apartmentSheet=workbook.Sheets['Apartamento'];
 const down=numberValue(labelValue(apartmentSheet,[/^entrada.*recursos proprios/,/^entrada$/],'B4')),fgts=numberValue(labelValue(apartmentSheet,[/^fgts utilizado/],'B5')),balance=numberValue(labelValue(apartmentSheet,[/^saldo devedor.*caixa/,/^saldo devedor atual$/],'B6'));
 if(down===null||fgts===null||balance===null)throw new Error('Valores monetários inválidos na aba Apartamento.');
 const rawContract=labelValue(apartmentSheet,[/^valor (de )?contrato/,/^valor.*compra e venda/],'B15'),contract=numberValue(rawContract),rawOriginal=labelValue(apartmentSheet,[/^valor financiado originalmente/,/^financiamento original/],'B17'),original=numberValue(rawOriginal)??balance,rawDate=labelValue(apartmentSheet,[/^data da compra/,/^data.*assinatura/],'B18'),purchaseDate=rawDate==null||rawDate===''?null:dateValue(rawDate),purchasePrice=contract??down+fgts+balance,filled=(value:unknown)=>value!=null&&String(value).trim()!=='';
 if(down<0||fgts<0||purchasePrice<=0||balance<0||balance>purchasePrice||original<0||(filled(rawContract)&&contract===null)||(filled(rawOriginal)&&numberValue(rawOriginal)===null)||(filled(rawDate)&&!purchaseDate))throw new Error('Dados financeiros inválidos na aba Apartamento.');
 const issues:ImportIssue[]=[],acquisitionCosts:SpreadsheetExpense[]=[],constructionFees:SpreadsheetExpense[]=[],seen=new Map<string,number>();
 const costs=workbook.Sheets['Custos de Aquisição'],costHeaders=findHeaders(costs,{date:[/^data$/,/data.*pagamento/],category:[/^categoria$/],description:[/^descricao$/],amount:[/^valor/],origin:[/^forma/,/^origem/],status:[/^status$/]});
 for(let row=costHeaders.row+1;row<=range(costs).e.r+1;row++){const get=(key:string)=>at(costs,costHeaders.columns[key],row),values=Object.keys(costHeaders.columns).map(get);if(values.every(v=>v==null||String(v).trim()===''))continue;const description=String(get('description')??'').trim(),categoryText=String(get('category')??'').trim(),combined=normalize(`${categoryText} ${description}`);if(/\b(total|subtotal|resumo)\b/.test(combined)){issues.push({sheet:'Custos de Aquisição',row,kind:'ignored',message:'Linha de totalização ou resumo.'});continue}if(/entrada|fgts/.test(combined)){issues.push({sheet:'Custos de Aquisição',row,kind:'ignored',message:'Entrada e FGTS já compõem os dados do imóvel.'});continue}if(normalize(get('status'))!=='pago'){issues.push({sheet:'Custos de Aquisição',row,kind:'ignored',message:'Status diferente de Pago.'});continue}const amount=numberValue(get('amount')),paidAt=dateValue(get('date'));if(amount===null||amount<=0||!description){issues.push({sheet:'Custos de Aquisição',row,kind:'warning',message:'Descrição ou valor inválido.'});continue}if(!paidAt||paidAt>today){issues.push({sheet:'Custos de Aquisição',row,kind:'warning',message:paidAt?'Data de pagamento futura.':'Data de pagamento inválida.'});continue}acquisitionCosts.push({category:categoryFor(categoryText,description)!,description,amount,paid_at:paidAt,notes:get('origin')?`Forma / origem: ${get('origin')}`:null,source_type:'spreadsheet',source_key:uniqueKey('acquisition',[paidAt,description],seen)})}
 const fees=workbook.Sheets['Taxas de Obra'],feeHeaders=findHeaders(fees,{period:[/^competencia$/],date:[/^data.*pagamento$/,/^data$/],amount:[/^valor/],balance:[/^saldo devedor/],progress:[/%.*obra/,/evolucao/],notes:[/^observacao$/],status:[/^status$/]});
 for(let row=feeHeaders.row+1;row<=range(fees).e.r+1;row++){const get=(key:string)=>at(fees,feeHeaders.columns[key],row),values=Object.keys(feeHeaders.columns).map(get);if(values.every(v=>v==null||String(v).trim()===''))continue;if(normalize(get('status'))!=='pago'){issues.push({sheet:'Taxas de Obra',row,kind:'ignored',message:'Status diferente de Pago.'});continue}const amount=numberValue(get('amount')),paidAt=dateValue(get('date')),period=periodValue(get('period'));if(amount===null||amount<=0||!period){issues.push({sheet:'Taxas de Obra',row,kind:'warning',message:'Competência ou valor inválido.'});continue}if(!paidAt||paidAt>today){issues.push({sheet:'Taxas de Obra',row,kind:'warning',message:paidAt?'Data de pagamento futura.':'Data de pagamento inválida.'});continue}const notes=[`Competência: ${period}`,get('balance')!=null&&`Saldo devedor informado: ${get('balance')}`,get('progress')!=null&&`Evolução da obra: ${get('progress')}`,get('notes')&&`Observação: ${get('notes')}`].filter(Boolean).join('\n');constructionFees.push({category:'construction_fee',description:`Taxa de obra ${period}`,amount,paid_at:paidAt,notes,source_type:'spreadsheet',source_key:uniqueKey('construction',[period],seen)})}
 return{apartment:{name:existingName||'Apartamento',purchase_price:purchasePrice,down_payment_amount:down,fgts_amount:fgts,original_financing_amount:original,current_financing_balance:balance,purchase_date:purchaseDate},acquisitionCosts,constructionFees,issues};
}
export async function readSpreadsheet(file:File,existingName?:string){if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('Selecione um arquivo .xlsx.');return parseWorkbook(XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),existingName)}
export function reconcileSpreadsheetExpenses(existing:Expense[],incoming:SpreadsheetExpense[],apartmentId:string,now:string,makeId:()=>string=()=>crypto.randomUUID()):Expense[]{const manual=existing.filter(item=>item.source_type!=='spreadsheet');const previous=new Map(existing.filter(item=>item.source_type==='spreadsheet').map(item=>[item.source_key,item]));return[...manual,...incoming.map(item=>{const old=previous.get(item.source_key);return{...item,apartment_id:apartmentId,id:old?.id||makeId(),created_at:old?.created_at||now,updated_at:now}})]}
