import {createContext,useCallback,useContext,useEffect,useState} from 'react'; import {configured,supabase} from './supabase'; import type {Apartment,ApartmentInput,Expense,ExpenseInput} from './types';
type Store={apartment:Apartment|null;expenses:Expense[];loading:boolean;error:string|null;demo:boolean;reload:()=>Promise<void>;saveApartment:(v:ApartmentInput)=>Promise<void>;saveExpense:(v:ExpenseInput,id?:string)=>Promise<void>;deleteExpense:(id:string)=>Promise<void>};
const Context=createContext<Store|null>(null); const localKey='lar-financas-demo';
const sort=(x:Expense[])=>[...x].sort((a,b)=>b.paid_at.localeCompare(a.paid_at)||b.created_at.localeCompare(a.created_at));
export function StoreProvider({children}:{children:React.ReactNode}){const [apartment,setApartment]=useState<Apartment|null>(null),[expenses,setExpenses]=useState<Expense[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{setLoading(true);setError(null);try{if(!configured){const data=JSON.parse(localStorage.getItem(localKey)||'{}');setApartment(data.apartment||null);setExpenses(sort(data.expenses||[]));return}const {data:a,error:ae}=await supabase!.from('apartments').select('*').order('created_at').limit(1).maybeSingle();if(ae)throw ae;setApartment(a);if(a){const {data:e,error:ee}=await supabase!.from('expenses').select('*').eq('apartment_id',a.id).order('paid_at',{ascending:false}).order('created_at',{ascending:false});if(ee)throw ee;setExpenses(e||[])}else setExpenses([])}catch{setError('Não foi possível carregar os dados.')}finally{setLoading(false)}},[]); useEffect(()=>{void reload()},[reload]);
 const persist=(a:Apartment|null,e:Expense[])=>localStorage.setItem(localKey,JSON.stringify({apartment:a,expenses:e}));
 async function saveApartment(v:ApartmentInput){if(configured){const query=apartment?supabase!.from('apartments').update(v).eq('id',apartment.id).select().single():supabase!.from('apartments').insert(v).select().single();const {data,error}=await query;if(error)throw error;setApartment(data)}else{const now=new Date().toISOString(),next={...v,id:apartment?.id||crypto.randomUUID(),created_at:apartment?.created_at||now,updated_at:now};setApartment(next);persist(next,expenses)}}
 async function saveExpense(v:ExpenseInput,id?:string){if(configured){const q=id?supabase!.from('expenses').update(v).eq('id',id):supabase!.from('expenses').insert(v);const {error}=await q;if(error)throw error;await reload()}else{const now=new Date().toISOString();const next=id?expenses.map(x=>x.id===id?{...x,...v,updated_at:now}:x):[...expenses,{...v,id:crypto.randomUUID(),created_at:now,updated_at:now}];setExpenses(sort(next));persist(apartment,next)}}
 async function deleteExpense(id:string){if(configured){const {error}=await supabase!.from('expenses').delete().eq('id',id);if(error)throw error;await reload()}else{const next=expenses.filter(x=>x.id!==id);setExpenses(next);persist(apartment,next)}}
 return <Context.Provider value={{apartment,expenses,loading,error,demo:!configured,reload,saveApartment,saveExpense,deleteExpense}}>{children}</Context.Provider>};
export const useStore=()=>{const x=useContext(Context);if(!x)throw new Error('StoreProvider ausente');return x};
