import {createContext,useCallback,useContext,useEffect,useState} from 'react';import {configured,supabase} from './supabase';import type {Apartment,ApartmentInput,Expense,ExpenseInput} from './types';import {reconcileSpreadsheetExpenses,type ImportPreview} from './spreadsheet';
type ImportResult={apartmentUpdated:number;expensesSynced:number;constructionFeesSynced:number};type Store={apartment:Apartment|null;expenses:Expense[];lastImport:string|null;loading:boolean;error:string|null;demo:boolean;reload:()=>Promise<void>;saveApartment:(v:ApartmentInput)=>Promise<void>;saveExpense:(v:ExpenseInput,id?:string)=>Promise<void>;deleteExpense:(id:string)=>Promise<void>;syncSpreadsheet:(preview:ImportPreview)=>Promise<ImportResult>};
const Context=createContext<Store|null>(null),localKey='lar-financas-demo';const sort=(items:Expense[])=>[...items].sort((a,b)=>b.paid_at.localeCompare(a.paid_at)||b.created_at.localeCompare(a.created_at));
export function StoreProvider({children}:{children:React.ReactNode}){const [apartment,setApartment]=useState<Apartment|null>(null),[expenses,setExpenses]=useState<Expense[]>([]),[lastImport,setLastImport]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{setLoading(true);setError(null);try{if(!configured){const data=JSON.parse(localStorage.getItem(localKey)||'{}');setApartment(data.apartment||null);setExpenses(sort(data.expenses||[]));setLastImport(data.lastImport||null);return}const {data:a,error:ae}=await supabase!.from('apartments').select('*').order('created_at').limit(1).maybeSingle();if(ae)throw ae;setApartment(a);if(a){const [{data:e,error:ee},{data:setting,error:se}]=await Promise.all([supabase!.from('expenses').select('*').eq('apartment_id',a.id).order('paid_at',{ascending:false}).order('created_at',{ascending:false}),supabase!.from('app_settings').select('value').eq('key','last_spreadsheet_import').maybeSingle()]);if(ee||se)throw ee||se;setExpenses(e||[]);setLastImport(setting?.value||null)}else{setExpenses([]);setLastImport(null)}}catch{setError('Não foi possível carregar os dados.')}finally{setLoading(false)}},[]);useEffect(()=>{void reload()},[reload]);
 const persist=(a:Apartment|null,e:Expense[],imported=lastImport)=>localStorage.setItem(localKey,JSON.stringify({apartment:a,expenses:e,lastImport:imported}));
 async function saveApartment(v:ApartmentInput){if(configured){const query=apartment?supabase!.from('apartments').update(v).eq('id',apartment.id).select().single():supabase!.from('apartments').insert(v).select().single();const {data,error}=await query;if(error)throw error;setApartment(data)}else{const now=new Date().toISOString(),next={...v,id:apartment?.id||crypto.randomUUID(),created_at:apartment?.created_at||now,updated_at:now};setApartment(next);persist(next,expenses)}}
 async function saveExpense(v:ExpenseInput,id?:string){if(configured){const {error}=await(id?supabase!.from('expenses').update(v).eq('id',id):supabase!.from('expenses').insert(v));if(error)throw error;await reload()}else{const now=new Date().toISOString(),next=id?expenses.map(x=>x.id===id?{...x,...v,updated_at:now}:x):[...expenses,{...v,id:crypto.randomUUID(),created_at:now,updated_at:now}];setExpenses(sort(next));persist(apartment,next)}}
 async function deleteExpense(id:string){if(configured){const {error}=await supabase!.from('expenses').delete().eq('id',id);if(error)throw error;await reload()}else{const next=expenses.filter(x=>x.id!==id);setExpenses(next);persist(apartment,next)}}
 async function syncSpreadsheet(preview:ImportPreview):Promise<ImportResult>{const importedAt=new Date().toISOString(),incoming=[...preview.acquisitionCosts,...preview.constructionFees];if(configured){const {error}=await supabase!.rpc('sync_spreadsheet_import',{p_apartment:preview.apartment,p_expenses:incoming,p_imported_at:importedAt});if(error)throw error;await reload()}else{const id=apartment?.id||crypto.randomUUID(),nextApartment={...preview.apartment,id,created_at:apartment?.created_at||importedAt,updated_at:importedAt},next=sort(reconcileSpreadsheetExpenses(expenses,incoming,id,importedAt));persist(nextApartment,next,importedAt);setApartment(nextApartment);setExpenses(next);setLastImport(importedAt)}return{apartmentUpdated:1,expensesSynced:preview.acquisitionCosts.length,constructionFeesSynced:preview.constructionFees.length}}
 return <Context.Provider value={{apartment,expenses,lastImport,loading,error,demo:!configured,reload,saveApartment,saveExpense,deleteExpense,syncSpreadsheet}}>{children}</Context.Provider>}
export const useStore=()=>{const value=useContext(Context);if(!value)throw new Error('StoreProvider ausente');return value};
